name: budgetapp_fl
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

  cupertino_icons: ^1.0.8

  http: ^1.2.1
  flutter_secure_storage: ^9.2.2

  dotted_border: ^3.1.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-Semibold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700